#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"

if [ $DOCKER_TAG = "latest" ]; then
	docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
else
	docker build --build-arg ARCH=$DOCKER_TAG -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi


echo "------ HOOK END - BUILD -------"
